apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vprodb
  namespace: default
  labels:
    app:  vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app:  vprodb
    spec:
      containers:
      - name:  vprodb
        image:  shipansm/vprofiledb:latest
        ports:
        - name: vprodb-port
          containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: vprodb-data
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
      nodeSelector:
        zone: us-east-1a
      volumes:
        - name: vprodb-data
          awsElasticBlockStore:
            volumeID: vol-083ac71a46b310b2e
            fsType: ext4
      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["rm","-rf","/var/lib/mysql/lost+found"]
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: vprodb-data
            

      